# Header
menu:
  Home: /
  Archives: /archives
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- recent_posts
- tag
- tagcloud
- archive

# Miscellaneous
google_analytics: UA-36983897-3
gauges_analytics:
favicon: /favicon.png
twitter: johnlcox
google_plus:
fb_admins:
fb_app_id:
